# Generated by Django 4.2.7 on 2023-11-29 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiGenres',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'api_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiGenresMovies',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'api_genres_movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiMoviecastingcredits',
            fields=[
                ('credit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('character', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_moviecastingcredits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiMovies',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255, unique=True)),
                ('movie_title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('runtime', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('audience_rating', models.FloatField()),
                ('num_ratings', models.IntegerField()),
            ],
            options={
                'db_table': 'api_movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiPeople',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255, unique=True)),
                ('person_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('death', models.DateField()),
                ('gender', models.IntegerField()),
                ('department', models.CharField()),
            ],
            options={
                'db_table': 'api_people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiPeoplealiases',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api_peoplealiases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('episode_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255)),
                ('episode_title', models.CharField(max_length=255)),
                ('chron_order', models.IntegerField(blank=True, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('audience_rating', models.FloatField(blank=True, null=True)),
                ('num_ratings', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'episodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieCrewCredits',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'movie_crew_credits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'movie_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieReviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255, unique=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_username', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=4095, null=True)),
                ('time_created', models.DateTimeField(blank=True, null=True)),
                ('time_updated', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=2047)),
            ],
            options={
                'db_table': 'movie_reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'providers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionProvidedMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.BooleanField()),
                ('rent_price', models.FloatField(blank=True, null=True)),
                ('buy', models.BooleanField()),
                ('buy_price', models.FloatField(blank=True, null=True)),
                ('flatrate', models.BooleanField()),
                ('flatrate_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region_provided_movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionProvidedSeasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.BooleanField()),
                ('rent_price', models.FloatField(blank=True, null=True)),
                ('buy', models.BooleanField()),
                ('buy_price', models.FloatField(blank=True, null=True)),
                ('flatrate', models.BooleanField()),
                ('flatrate_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region_provided_seasons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionProvidedShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.BooleanField()),
                ('rent_price', models.FloatField(blank=True, null=True)),
                ('buy', models.BooleanField()),
                ('buy_price', models.FloatField(blank=True, null=True)),
                ('flatrate', models.BooleanField()),
                ('flatrate_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region_provided_shows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('iso', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'regions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonCastingCredits',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('character', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'season_casting_credits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonCrewCredits',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'season_crew_credits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255)),
                ('season_title', models.CharField(max_length=255)),
                ('chron_order', models.IntegerField(blank=True, null=True)),
                ('num_episodes', models.IntegerField(blank=True, null=True)),
                ('audience_rating', models.FloatField(blank=True, null=True)),
                ('num_ratings', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seasons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowCastingCredits',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('character', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'show_casting_credits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowCrewCredits',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'show_crew_credits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowGenres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'show_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShowReviews',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255, unique=True)),
                ('author_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_username', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=4095, null=True)),
                ('time_created', models.DateTimeField(blank=True, null=True)),
                ('time_updated', models.DateTimeField(blank=True, null=True)),
                ('origin', models.CharField(max_length=255)),
                ('reference', models.CharField(max_length=2047)),
            ],
            options={
                'db_table': 'show_reviews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255, unique=True)),
                ('show_title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('initial_release', models.DateField(blank=True, null=True)),
                ('final_release', models.DateField(blank=True, null=True)),
                ('num_episodes', models.IntegerField(blank=True, null=True)),
                ('num_seasons', models.IntegerField(blank=True, null=True)),
                ('in_production', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'shows',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='moviecastingcredits',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='people',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='peoplealiases',
            options={'managed': False},
        ),
    ]
